removeLines:
  class: src.processors.one_channel_processor.BlackLineRemoval
  params:
    channel: 0
    size: [1024, 1024]
    value: 0
    logRowCols: False
    countPixels: False
    dictionary: output\GRAYSCALE_TREATED\blackLineCropDictionary-2024-01-07-16-07-32\blackLineLog.json
    dictionaryRGBtoAMatch: output\Match_RGB_Elevation\matchRGBtoA.json
scale:
  class: src.processors.one_channel_processor.Scale
  params:
    channel: 0
    type: "iExp"
    mean: 0.08812050886132342 #0.11549015741807088
    min: -415
    max: 8729
rescale:
  class: src.processors.one_channel_processor.Rescale
  params:
    channel: 0
    type: "iExp"
    min: 0
    max: 255
stdDev:
  class: src.processors.one_channel_processor.StdDevSort
  params:
    channel: 3
    limit: 3.5  #4.5
edges:
  class: src.processors.one_channel_processor.EdgeDetection
  params:
    channel: 0
    
kMeans:
  class: src.processors.one_channel_processor.KMeansSegmentation
  params:
    channel: 0
    k: 4

medianDenoise:
  class: src.processors.one_channel_processor.MedianDenoise
  params:
    channel: 0

crop:
  class: src.processors.process.Crop
  params:
    size: [1024, 1024]
tile:
  class: src.processors.process.Tile
  params:
    size: [256, 256]
8bit:
  class: src.processors.process.To8bit
  params:
    min: 0
    max: 255
    # min: -415
    # max: 8729
sizeCheck:
  class: src.processors.process.SizeCheckSort
  params:
    size: [1024,1024]
    type: exact   #less
changeMode:
  class: src.processors.process.ChangeMode
  params:
    mode: L
    format: png
info:
  class: src.processors.process.Info
  params: None


    

brightness:
  class: src.processors.rgb_processor.BrightnessSort
  params: Null


datasetSplit:
  class: src.processors.batch_processor.DatasetSplit
  params:
    shuffle: True
    valPercent: 0.20
makeHistogram:
  class: src.processors.batch_processor.HistogramAnalysis
  params:
    bit_depth: s16bit
    size: [1024, 1024] # [256, 256]
    image_type: "GS"
    # pixel_range: 9144   #max: 8729
    # min: -415
openHistogram:
  class: src.processors.batch_processor.HistogramAnalysis
  params:
    bit_depth: s16bit
    size: [1024, 1024] # [256, 256]
    image_type: "GS"
    # pixel_range: 9144   #max: 8729
    # min: -415

compare:
  class: src.processors.two_data_processor.Compare
  params:
    data_target: D:\StableDiffusion\Datasets\earth-engine-image-tool\output\RGB\removeLines-2024-01-07-18-22-14
    exitOnDifferent: False
subtract:
  class: src.processors.two_data_processor.Subtract
  params:
    channels_to_compare: [0,1,2]
    nbr_channels: 4
    data_target:  C:\Users\Margarida\OneDrive - Universidade de Lisboa\Desktop\Logs\img\re
    #D:\StableDiffusion\stable-diffusion-terrain\logs\2024-01-19T10-44-52_RGBA_Loss_autoencoder_kl_64x64x4\samples\2024-01-24-16-05-13\img\re



mergeRGBA: 
  class: src.processors.rgba_processor.MergeRGBandA
  params: 
    dictionary: D:\StableDiffusion\Datasets\earth-engine-image-tool\output\RGBA\matchRGBA-2024-01-26-00-48-57\matchRGBtoA.json
    alpha_target: D:\StableDiffusion\Datasets\earth-engine-image-tool\output\Grayscale_correct_mean_iexp_w_stddev_3.5\iExp_scale-2024-01-25-12-09-13
separateRGBA:
  class: src.processors.rgba_processor.SeparateRGBFromA
  params: None
matchRGBA:
  class: src.processors.rgba_processor.MatchRGBA
  params: 
    merge: False
    rgb_target: output\RGB\crop-2024-01-07-18-22-14 #'data\\RGB\\ThirdBatch\\EuropeRGB'
    rgb_format: png
    # rgb_log:  logs\name_to_coordinate_dict.log
    rgb_json: logs\rgb.json
    a_log:  logs\europeElevationLogs\name_to_coordinate_dict.log
    #a_json: logs\europeElevationLogs\gs.json
    alpha_format: png

