removeLines:
  class: process.BlackLineRemoval
  params:
    channel: 4
    size: [1024, 1024]
    value: 0
crop:
  class: process.Crop
  params:
    size: [1024, 1024]
tile:
  class: process.Tile
  params:
    size: [256, 256]
8bit:
  class: process.To8bit
  params:
    min: 0
    max: 255
    # min: -415
    # max: 8729
scale:
  class: process.Scale
  params:
    channel: 4
    type: "iExp"
    min: -415
    max: 8729
rescale:
  class: process.Rescale
  params:
    type: "iExp"
    min: 0
    max: 255
stdDev:
  class: process.StdDevSort
  params:
    channel: 4
    limit: 3.5  #4.5
brightness:
  class: process.BrightnessSort
  params: Null


datasetSplit:
  class: datasetSplit.DatasetSplit
  params:
    shuffle: True
    valPercent: 0.15
histogram:
  bit_depth: u16bit
  # use_pickle: ""
  size: [256, 256] #[1024,1024]
  image_type: "RGBA"